---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        enabled: true
        state: restarted
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        enabled: true
        state: restarted

  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        disable_gpg_check: true
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Drop database
      ansible.builtin.command: "clickhouse-client -q 'drop database logs;'"      
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and fycreate_db.rc !=82
      changed_when: create_db.rc == 0
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: https://setup.vector.dev
        dest: "./repo.sh"
    - name: Install vector repo
      become: true
      ansible.builtin.command: /bin/bash ./repo.sh
        
    - name: Install vector
      become: true
      ansible.builtin.yum: 
        name:
          - vector
      notify: Start vector service
    - name: Create vector config dir
      become: true
      ansible.builtin.file:
        state: directory
        owner: vector
        group: vector
        mode: 750
        path: /etc/vector
        
              
